var namespaces =
[
    [ "AliTPCDcalibRes", "d9/d50/namespaceAliTPCDcalibRes.html", null ],
    [ "arrow", "d6/d7f/namespacearrow.html", "d6/d7f/namespacearrow" ],
    [ "boost", "d4/da9/namespaceboost.html", null ],
    [ "cuda_cub", "dc/dc9/namespacecuda__cub.html", null ],
    [ "ex2", "d4/d8f/namespaceex2.html", null ],
    [ "ex3", "d2/d51/namespaceex3.html", null ],
    [ "ex4", "d9/dc8/namespaceex4.html", null ],
    [ "gNeric", "df/d36/namespacegNeric.html", null ],
    [ "GPUCA_NAMESPACE", "db/df1/namespaceGPUCA__NAMESPACE.html", "db/df1/namespaceGPUCA__NAMESPACE" ],
    [ "GPUTPCDefinitions", "d1/dff/namespaceGPUTPCDefinitions.html", null ],
    [ "HepMC", "d1/d98/namespaceHepMC.html", null ],
    [ "nlohmann", "d3/d9b/namespacenlohmann.html", "d3/d9b/namespacenlohmann" ],
    [ "nodes", "d1/d51/namespacenodes.html", null ],
    [ "o2", "d4/d7c/namespaceo2.html", "d4/d7c/namespaceo2" ],
    [ "painter", "d0/d06/namespacepainter.html", null ],
    [ "Pythia8", "d3/dee/namespacePythia8.html", null ],
    [ "qConfig", "d6/dc3/namespaceqConfig.html", null ],
    [ "RawReaderEventSync", "d1/d88/namespaceRawReaderEventSync.html", null ],
    [ "ROOT", "d0/d10/namespaceROOT.html", "d0/d10/namespaceROOT" ],
    [ "std", "d8/dcc/namespacestd.html", null ],
    [ "test", "df/d04/namespacetest.html", null ],
    [ "utils", "d6/d84/namespaceutils.html", null ]
];